# Generated by Django 5.1.2 on 2024-10-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
